stages:
  - build
  - deploy

build_image:
  stage: build
  only:
    refs:
      - /^(main|develop.*)$/
    changes:
      - src/api/**
      - src/utils/**
      - src/*
      - ci/*
      - Dockerfile
      - requirements.txt
      - cloud_environments_prod.yml
      - docker-compose-build.yml
      - docker-compose-prod.yml
  tags:
    - imagesbuilder
  script:
    - chmod +x ./ci/deliver.sh
    - ./ci/deliver.sh

deploy_image:
  stage: deploy
  needs:
    - build_image
    - scan_image
    - unittest
  script:
    - chmod +x ./ci/deploy.sh
    - ./ci/deploy.sh
  only:
    refs:
      - /^(main|develop.*)$/
    changes:
      - src/api/**
      - src/utils/**
      - src/*
      - ci/*
      - Dockerfile
      - requirements.txt
      - cloud_environments_prod.yml
      - docker-compose-build.yml
      - docker-compose-prod.yml
  tags:
    - web
